AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template to Create an EC2 Instance and an S3 Bucket

Parameters:
  InstanceType:
    Description: Type of EC2 instance to create
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
    ConstraintDescription: Must be a valid EC2 instance type.

  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: Must be the name of an existing KeyPair.

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "my-s3-bucket-${AWS::AccountId}-${AWS::Region}"
      AccessControl: Private

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: ami-0ed194d7eff6d2f81 # Amazon Linux 2 AMI (replace with the desired AMI ID for your region)
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      Tags:
        - Key: Name
          Value: CloudFormation-EC2-Instance

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access to the EC2 instance
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

Outputs:
  S3BucketName:
    Description: Name of the created S3 bucket
    Value: !Ref S3Bucket

  InstancePublicIp:
    Description: Public IP address of the created EC2 instance
    Value: !GetAtt EC2Instance.PublicIp
